module.exports = {
  TOKEN_SECRET: process.env.TOKEN_SECRET || 'SECRET',

  FACEBOOK_SECRET: process.env.FACEBOOK_SECRET || 'a8fa21e754f6ad0f21ab615c4c101d02',
  GOOGLE_SECRET: process.env.GOOGLE_SECRET || 'HNU0Ebbps7g5D1Q1bu1ErECb',
  GITHUB_SECRET: process.env.GITHUB_SECRET || 'YOUR_GITHUB_CLIENT_SECRET'
};
